name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build apps.json
        uses: loveloper44/render-json-action@v2.0.2
        id: render
        env:
          REPO_URL: https://token:${{ github.token }}@github.com/${{ github.repository }}
          REPO_BRANCH: "main"
        with:
          json: ./apps.json

      - name: Load apps.json to environment
        run: echo "APPS_JSON_BASE64=$(base64 --wrap=0 ${{ steps.render.outputs.result }})" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          file: ./docker/Containerfile
          push: true
          build-args: |
            APPS_JSON_BASE64=${{ env.APPS_JSON_BASE64 }}
            FRAPPE_PATH=https://github.com/frappe/frappe
            FRAPPE_BRANCH=version-14

          tags: |
            ahuahuachi/erpnext_mexico_compliance:latest
